image: "golang:1.13"

before_script:
  - mkdir -p /go/src/github.com/katzenpost
  - cp -r /builds/katzenpost/* /go/src/github.com/katzenpost/
  - cd /builds/katzenpost/catshadow/

test-catshadow:
  script:
    - mkdir -p coverage
    - go test -v -coverprofile cover.out -covermode atomic -coverpkg ./... -race ./...
    - go tool cover -html=cover.out -o coverage/coverage.html
  artifacts:
    paths:
      - coverage/
